[project]
name = "brain"
version = "0.1.0"
description = "second braaaain"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anthropic>=0.79.0",
    "langchain>=1.2.10",
    "langchain-anthropic>=1.3.3",
    "langgraph>=1.0.8",
    "neo4j>=5.28.3",
    "neo4j-graphrag>=1.1.0",
    "pydantic-settings>=2.12.0",
    "python-dotenv>=1.2.1",
    "python-frontmatter>=1.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.1",
    "ty>=0.0.16",
]

[tool.ruff]
target-version = "py314"
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "W"]
